### ISSUE TITLE
SQLLite Error on Importing Scraper

### ISSUE THREAD

**Issue by whatamithinking** [Eezzeldin/LinkedinEasyApplybot#1]
Hi there, I just tried to import your files and I get the following error on importing Scraper.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\conno\Downloads\LinkedinEasyApplybot-master\LinkedinEasyApplybot-master\Applier.py", line 38, in <module>
    urls = cur.execute('''SELECT DISTINCT * FROM Python3 ''')
sqlite3.OperationalError: no such table: Python3

**Comment by vishwanathakuthota** [comment]
Hey Check if your code is calling sqlite3 in the code and give it admin privileges.
